### ISSUE TITLE
[feature-request] Store state of ERD diagram for reproducing with ease or sharing

### ISSUE THREAD

**Issue by gavindsouza** [The-Commit-Company/commit#53]
Selecting many doctypes and reloading or closing browser tab by mistake leads to a loss of generated diagrams. A mechanism that would store state of generated diagrams would enhance usability.

Possible solutions:

* Storing state of diagram in the URL (share-able, not sure if possible)
* Storing state in localstorage (local, but persistent)

**Comment by sumitjain236** [comment]
Will Try with Storing state in localStorage
