### ISSUE TITLE
Missing Generate ERD button

### ISSUE THREAD

**Issue by rtdany10** [The-Commit-Company/commit#56]
Generate ERD button seems to be missing after selecting doctypes
![image](https://github.com/user-attachments/assets/3e7a3680-9758-4769-b3da-715c10039645)

**Comment by sumitjain236** [comment]
> Generate ERD button seems to be missing after selecting doctypes ![image](https://private-user-images.githubusercontent.com/52111700/352547449-3e7a3680-9758-4769-b3da-715c10039645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODc5MDQsIm5iZiI6MTcyMjA4NzYwNCwicGF0aCI6Ii81MjExMTcwMC8zNTI1NDc0NDktM2U3YTM2ODAtOTc1OC00NzY5LWIzZGEtNzE1YzEwMDM5NjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEzNDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NmFmNmZmMWRiN2FlZjk3YzAyZTE5YTEyZTc5YTQ5YzFkZmU3Y2Q0N2I3ZWUzMzBjNzY0ZjhhY2I0NmYzYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.12saG2cPKCpkYHrt3u9KYzoZTcnwiW7OjkNXH_1p8io)

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/732c3179-8824-448f-be86-1544279ae66a">

It is there, Can You describe on which Scenario button not appears

**Comment by rtdany10** [comment]
https://github.com/user-attachments/assets/b3bacace-cfb2-44a3-a375-63f571ace36e

doesn't show up at all

**Comment by sumitjain236** [comment]
@rtdany10 there is major Changes in UI can you update your codebase and can check if issue is still there

**Comment by rtdany10** [comment]
> @rtdany10 there is major Changes in UI can you update your codebase and can check if issue is still there

https://commit.frappe.cloud/commit/project-erd
![image](https://github.com/user-attachments/assets/6c5b5181-963a-476d-99ea-5eaf29527538)
![image](https://github.com/user-attachments/assets/e9d9a605-d4e3-492c-8252-2886a22014ed)

**Comment by sumitjain236** [comment]
@rtdany10 well we figure it out that this problem was in firefox browser, so we tried to fix that can you check once

**Comment by rtdany10** [comment]
Thanks @sumitjain236
