### ISSUE TITLE
Copy to Clipboard buttons don't work while commit is running locally.

### ISSUE THREAD

**Issue by Mangeshrex** [The-Commit-Company/commit#61]
Hi Team, 

I am running commit locally and I am trying to copy some of the endpoints in bruno on the system. But after clicking on the link there is nothing which is getting copied and the clipboard is empty. 

As you can see in the screenkey bottom panel that I am trying to press Ctrl + v but that doesn't copy anything into the bruno input.

Here's a demo of the error: 

[copy-to-clipboard.webm](https://github.com/user-attachments/assets/9675b3a2-62da-4b5c-84ad-4276e13d83ce)

**Comment by sumitjain236** [comment]
> Hi Team,
> 
> I am running commit locally and I am trying to copy some of the endpoints in bruno on the system. But after clicking on the link there is nothing which is getting copied and the clipboard is empty.
> 
> As you can see in the screenkey bottom panel that I am trying to press Ctrl + v but that doesn't copy anything into the bruno input.
> 
> Here's a demo of the error:
> 
>  copy-to-clipboard.webm

Have you tried to paste this on text editor or somewhere else to check is it getting copy or not ?

**Comment by Mangeshrex** [comment]
Hey nope, I'll try doing that and get back to you.

**Comment by sumitjain236** [comment]
@Mangeshrex  have you tried again

**Comment by sumitjain236** [comment]
@Mangeshrex  have you tried again

**Comment by Mangeshrex** [comment]
Hey, yes. I tried but that didn't work. I am guessing nothing is getting copied to the clipboard at the first place.

**Comment by Mangeshrex** [comment]
[kazam_afv6b5_h.gif.webm](https://github.com/user-attachments/assets/2694b23e-b496-4403-abb5-39ceb8efd727)


here's another live try I did.

**Comment by Mangeshrex** [comment]
@sumitjain236 Tried searching a bit here and there about the error clipboard error. Looks like this problem is happening because of the browser versioning moreover. 

I get different errors 

-  on Mozilla Zen 1.0.0-a.30: 

`Failed to copy:  TypeError: navigator.clipboard is undefined` 

- Firefox (Mozilla Firefox 132.0a1) 

`TypeError: can't access property "writeText", navigator.clipboard is undefined` 

- Chromium (128.0.6613.119)

`TypeError: Cannot read properties of undefined (reading 'writeText')`

**Comment by Mangeshrex** [comment]
Hey @sumitjain236, sorry if you're busy. But, if this issue is relevant and legit, I'd be happy to give a try at fixing this and making a PR :).

**Comment by nikkothari22** [comment]
@Mangeshrex Looks like `navigator.clipboard` is not available on the browser you are using. Can you try entering this in the browser console: `navigator.clipboard.writeText("Hello")`

**Comment by Mangeshrex** [comment]
![Capture-Sep-18-22-55-02](https://github.com/user-attachments/assets/871dd568-6c56-44c4-83b0-7b3a0b029d46)

**Comment by Mangeshrex** [comment]
Funnily enough, what you told `navigator.clipboard.writeText("Hello")` did not work and it returned navigator is undefined error.

I entered just `navigator` in the console and turns out my version of Firefox/Chromium supports `navigator.clipboard` . So, I ran `navigator.clipboard.read("hello")` and then `navigator.clipboard.write("Hello")` and it successfully copied the text. 

![Capture-Sep-18-23-09-53](https://github.com/user-attachments/assets/4b44f420-2305-489f-bb23-a21205725ad2)

P.S: I am no JS pro, so please let me know if there's anything dumb in the above 😅.

**Comment by sumitjain236** [comment]
The navigator.clipboard API is only available in secure contexts, meaning it works only on pages served over HTTPS or on localhost. If you're running this script on an HTTP site, it will throw the error because the Clipboard API is not available in insecure contexts.

@Mangeshrex can you check this ?

**Comment by Mangeshrex** [comment]
Hey, yes I know about this. I read about this in [Frappe's code](https://github.com/frappe/frappe/blob/e8153fc2b67c92558fd2ac86eb66dbae07cc07fe/frappe/public/js/frappe/utils/utils.js#L1040).

so, should I try running commit locally on https ? I'll try generating a self signed SSL Cert for my local site.

**Comment by sumitjain236** [comment]
Yes you can try there or you can try at http:localhost:{port} where port is on which your bench running

**Comment by Mangeshrex** [comment]
>http:localhost:{port}

Wait, wouldn't that show 404 or page not found ? Since bench would serve the page on the site url ? 

Additionally, to prove myself wrong I did remove the lines redirecting 127.0.0.1 -> commit.site from the `/etc/hosts` file.

**Comment by Mangeshrex** [comment]
:) sadly none of them works. Does clipboard give you no errors on your end ?

![Capture-Sep-20-18-24-42](https://github.com/user-attachments/assets/d267adb8-25fe-496d-9164-e0a61eb9e9fd)

**Comment by sumitjain236** [comment]
No we dont have such error, whats the error you get there check once may be your bench is not started may be

**Comment by Mangeshrex** [comment]
Ahh, it works fine and my bench is running fine. 

Anyways, The discussion seems to be going too long needlessly. I think this issue would just waste your time as you can't reproduce it on your end. I'll try and hunt for something or else close this issue. 

Thank You
